### PR TITLE
To enable windows to build at javadoc-plugin section.

### PR DESCRIPTION
**Pull request by yasu-sh**
Only checked windows/Java 11 in Cdrive. But I think it works for Mac/Unix also. Checked Internet information.

### CODE REVIEW

**Comment by kvb2univpitt** [comment]
@yasu-sh This doesn't work for me.  I got the following error.

```console
[INFO] --- maven-javadoc-plugin:3.4.1:jar (attach-javadocs) @ causal-cmd ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.034 s
[INFO] Finished at: 2023-03-15T22:48:10-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.4.1:jar (attach-javadocs) on project causal-cmd: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The javadoc executable '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b09-1.fc36.x86_64/jre/bin/javadoc' doesn't exist or is not a file. Verify the <javadocExecutable/> parameter. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by yasu-sh** [comment]
@kvb2univpitt Thanks for telling me. I see. Let me check the background.

**Comment by yasu-sh** [comment]
@kvb2univpitt I now understand the place is changed by developers as preferred. Sorry to bother you.
I think it is okay as original. I can change if needed. After your reply, I'll just close this.

- jdk folder
image

- jre folder
image

**Comment by kvb2univpitt** [comment]
Sounds good.  Thanks.

**Comment by yasu-sh** [comment]
Closing.

**Pull request closed without merging**
